package examples.basic;

/**
 * Created by ceruleanhu on 5/15/14.
 */
public enum CcyPair {
    BTCUSD,BTCHKD,BTCEUR,BTCCAD,BTCAUD,BTCSGD,BTCJPY,BTCCHF,BTCGBP,BTCNZD,
    LTCBTC, LTCUSD, LTCHKD,LTCEUR,LTCCAD,LTCAUD,LTCSGD,LTCJPY,LTCCHF,LTCGBP,LTCNZD,
    PPCBTC, PPCLTC,PPCUSD, PPCHKD,PPCEUR,PPCCAD,PPCAUD,PPCSGD,PPCJPY,PPCCHF,PPCGBP,PPCNZD,
    NMCBTC, NMCLTC,NMCUSD, NMCHKD,NMCEUR,NMCCAD,NMCAUD,NMCSGD,NMCJPY,NMCCHF,NMCGBP,NMCNZD,
    DOGEBTC, DOGEUSD, DOGEHKD,DOGEEUR,DOGECAD,DOGEAUD,DOGESGD,DOGEJPY,DOGECHF,DOGEGBP,DOGENZD;
}
